apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs02-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CSO2/cs02-computer-store.git
    targetRevision: HEAD
    path: k8s/services
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
