apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cso2-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CSO2/Infrastructure.git
    targetRevision: main
    path: cso2/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cso2-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cso2-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CSO2/Infrastructure.git
    targetRevision: dev
    path: cso2/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: cso2-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

