apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vault-secret-store.yaml
- redis-external-secret.yaml
- postgresql-external-secret.yaml
- mongodb-external-secret.yaml
- user-identity-service-external-secret.yaml
- product-catalogue-service-external-secret.yaml
- order-service-external-secret.yaml
- shoppingcart-wishlist-service-external-secret.yaml
- support-service-external-secret.yaml
- content-service-external-secret.yaml
- notifications-service-external-secret.yaml
- reporting-and-analysis-service-external-secret.yaml
