apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: mongodb-secrets
    creationPolicy: Owner
  data:
  - secretKey: MONGO_INITDB_ROOT_USERNAME
    remoteRef:
      key: secret/data/cso2/dev/mongodb
      property: MONGO_INITDB_ROOT_USERNAME
  - secretKey: MONGO_INITDB_ROOT_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/mongodb
      property: MONGO_INITDB_ROOT_PASSWORD
