apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifications-service-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: notifications-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: MONGODB_URI
  - secretKey: MAIL_USERNAME
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: MAIL_USERNAME
  - secretKey: MAIL_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: MAIL_PASSWORD
  - secretKey: ADMIN_EMAIL
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: ADMIN_EMAIL
  - secretKey: TWILIO_ACCOUNT_SID
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: TWILIO_ACCOUNT_SID
  - secretKey: TWILIO_AUTH_TOKEN
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: TWILIO_AUTH_TOKEN
  - secretKey: TWILIO_PHONE_NUMBER
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: TWILIO_PHONE_NUMBER
  - secretKey: FIREBASE_CONFIG_PATH
    remoteRef:
      key: secret/data/cso2/dev/notifications-service
      property: FIREBASE_CONFIG_PATH
