apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secret/data/cso2/dev/postgresql
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/postgresql
      property: POSTGRES_PASSWORD
  - secretKey: CSO2_USER
    remoteRef:
      key: secret/data/cso2/dev/postgresql
      property: CSO2_USER
  - secretKey: CSO2_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/postgresql
      property: CSO2_PASSWORD
