apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: product-catalogue-service-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: product-catalogue-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: secret/data/cso2/dev/product-catalogue-service
      property: MONGODB_URI
