apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: redis-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/redis
      property: REDIS_PASSWORD
