apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shoppingcart-wishlist-service-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: shoppingcart-wishlist-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: secret/data/cso2/dev/shoppingcart-wishlist-service
      property: MONGODB_URI
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/shoppingcart-wishlist-service
      property: REDIS_PASSWORD
