apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: support-service-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: support-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/support-service
      property: DATABASE_PASSWORD
  - secretKey: MONGODB_URI
    remoteRef:
      key: secret/data/cso2/dev/support-service
      property: MONGODB_URI
  - secretKey: ORDER_SERVICE_URL
    remoteRef:
      key: secret/data/cso2/dev/support-service
      property: ORDER_SERVICE_URL
