apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-identity-service-secrets
  namespace: cso2-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-dev
    kind: SecretStore
  target:
    name: user-identity-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: secret/data/cso2/dev/user-identity-service
      property: DATABASE_PASSWORD
  - secretKey: MONGODB_URI
    remoteRef:
      key: secret/data/cso2/dev/user-identity-service
      property: MONGODB_URI
  - secretKey: JWT_PRIVATE_KEY
    remoteRef:
      key: secret/data/cso2/dev/user-identity-service
      property: JWT_PRIVATE_KEY
  - secretKey: JWT_PUBLIC_KEY
    remoteRef:
      key: secret/data/cso2/dev/user-identity-service
      property: JWT_PUBLIC_KEY
