apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-dev
  namespace: cso2-dev
spec:
  provider:
    vault:
      server: http://vault.cso2-dev.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: cso2-dev-external-secrets
