apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: cso2-dev
type: Opaque
stringData:
  # These values should be overwritten by environment-specific overlays or sealed secrets
  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "changeme"
