apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  labels:
    app: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: cso2/content-service:latest
        ports:
        - containerPort: 8086
        env:
        - name: DB_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content-service
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
