apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  labels:
    app: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - name: notifications-service
        image: cso2/notifications-service:latest
        ports:
        - containerPort: 8087
        env:
        - name: DB_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - protocol: TCP
    port: 8087
    targetPort: 8087
