apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue-service
  labels:
    app: product-catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalogue-service
  template:
    metadata:
      labels:
        app: product-catalogue-service
    spec:
      containers:
      - name: product-catalogue-service
        image: cso2/product-catalogue-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/CSO2_product_catalogue_service" # Update host
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-service
spec:
  selector:
    app: product-catalogue-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
