apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-wishlist-service
  labels:
    app: shoppingcart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart-service
  template:
    metadata:
      labels:
        app: shoppingcart-service
    spec:
      containers:
      - name: shoppingcart-service
        image: cso2/shoppingcart-wishlist-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: DB_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-wishlist-service
spec:
  selector:
    app: shoppingcart-service
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
