---
- hosts: all
  become: yes
  roles:
    - common

- hosts: role_control_plane
  become: yes
  roles:
    - control_plane
    - opensearch

- hosts: role_worker
  become: yes
  roles:
    - worker

# OpenSearch is now deployed on control plane, remove separate host group
# - hosts: opensearch
#   become: yes
#   roles:
#     - opensearch
