apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: content-service-secrets
  namespace: cso2-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-prod
    kind: SecretStore
  target:
    name: content-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: MONGODB_URI
    remoteRef:
      key: secret/data/cso2/prod/content-service
      property: MONGODB_URI
