apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: cso2-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-prod
    kind: SecretStore
  target:
    name: redis-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: secret/data/cso2/prod/redis
      property: REDIS_PASSWORD
