apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reporting-and-analysis-service-secrets
  namespace: cso2-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-prod
    kind: SecretStore
  target:
    name: reporting-and-analysis-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: secret/data/cso2/prod/reporting-and-analysis-service
      property: DATABASE_PASSWORD
