apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-prod
  namespace: cso2-prod
spec:
  provider:
    vault:
      server: https://vault.cso2-prod.internal
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: cso2-prod-external-secrets
